version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
